### ISSUE TITLE
Incompatible change in pylint 2.0.0 

### ISSUE THREAD

**Issue by tobias-hd** [johnnoone/setuptools-pylint#13]
setuptools-lint seems not to run with the latest release 2.0.0 of pylint (https://pylint.readthedocs.io/en/latest/whatsnew/2.0.html). 

Whereas running pylint directly does work on my coding, running setuptools-lint aborts in 2 different projects with the same error message:

```
# python setup.py lint
running lint
running egg_info
writing phypy.egg-info/PKG-INFO
writing dependency_links to phypy.egg-info/dependency_links.txt
writing requirements to phypy.egg-info/requires.txt
writing top-level names to phypy.egg-info/top_level.txt
reading manifest file 'phypy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'phypy.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    'Programming Language :: Python :: 3.6'
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/setuptools_lint/setuptools_command.py", line 145, in run
    {'exit': False})
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/setuptools_lint/setuptools_command.py", line 104, in with_project_on_sys_path
    return func(*func_args, **func_kwargs)
TypeError: __init__() got an unexpected keyword argument 'exit'
```

setup.py is clean and has no syntax problems. pylint directly does work, also setuptools-lint did run successfully with pylint 1.9.2. Hence I guess there is some problem in the way setuptools-lint calls pylint.

**Comment by vhamon** [comment]
Same with pylint 2.1.1

**Comment by johnnoone** [comment]
I've pushed a new version on pypi, it should work now https://pypi.org/project/setuptools-lint/

**Comment by vhamon** [comment]
Thanks. I confirm it works now with 0.6.0

**Comment by tobias-hd** [comment]
Yes, this is fixed. Thanks!
